### PR TITLE
Add ie id enum

### PR DESCRIPTION
**Pull request by chunmeng**

### CODE REVIEW

**Comment by grrtrr** [comment]
Hi thank you for the PR. This looks interesting. It is a larger change so may take a couple of iterations to integrate.

I am happy to look at this later.

**Comment by alicektx** [comment]
...was this closed by accident or something previously? :-/
The 2 extra filtering options can come up pretty handy for crowded environments,
and don't look much intrusive i'd think. Any thoughts grrtrr?

**Comment by grrtrr** [comment]
I didn't close this.

**Comment by alicektx** [comment]
...just noticed that 7919687 above, 
assigns the 'h' shortcut for on-the-fly filtering of the 'hidden' essids:
such makes sense and is also very nice in terms of mnemonics, h for hidden,
but it appears to currently 'hijack' the current shortcut for [help screen](https://github.com/uoaerg/wavemon/blob/master/wavemon.c#L253-L257).
Not sure myself how someone should go about it eventually..

The band display filtering works pretty great though (thanks chunmeng!)
grrtrr, not really experienced with c / ncurses, some basic python skills here & there,
but i made a stripped down pull request of the band filtering feature,
in case you want to consider it for proper inclusion at some point.
I sincerely hope i'm not bothering you or wasting your time here,
and sorry in advance if such is the case...

**Comment by grrtrr** [comment]
@chunmeng - any comments on this?

**Comment by grrtrr** [comment]
> ...just noticed that [7919687](https://github.com/uoaerg/wavemon/commit/7919687d43e1e3ce22a63ffd7d743e807a8972cf) above, assigns the 'h' shortcut for on-the-fly filtering of the 'hidden' essids:

That is the reason I want to shelve this for a while. The sorting keyboard shortcuts are already difficult to memorize and handle.
The above one would  conflict with `h`, while the ones in #77 would conflict with those of #76 (which is going to be added).
To resolve these, a _separate way_ of setting up filters / sort options for the Scan Screen is needed; likely on a different screen.

**Comment by grrtrr** [comment]
@chunmeng - can you please _re-submit_ your PR or get in contact?

I want to start integrating the work that you submitted, beginning at the header for IE enums, the display of extended capabilities, and then the filter options. As @alicektx 's Pull Request shows, there is still interest in your work. Please get in contact.

**Pull request closed without merging**
